- name: Play level vars
  hosts: all
  vars:
    URL: play.google.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}

- name: Play level variables from files
  hosts: all
  vars_files:
    - sample-vars.yml
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}


- name: Task level variables
  hosts: all
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}
      vars:
        URL: tasks.google.com

#if we declare var at task level the only that task can access the variable

- name: inventory level variables
  hosts: all
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}