- name: Play level vars
  hosts: all
  vars:
    URL: play.google.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}

- name: Play level variables from files
  hosts: all
  vars_files:
    - sample-vars.yml
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}
