- name: Configure YUM repos.
  ansible.builtin.shell: curl -fsSL https://rpm.nodesource.com/setup_lts.x | bash -

- name: Install NodeJS
  ansible.builtin.yum:
    name:
      - nodejs
      - gcc-c++
    state: installed

- name: Download and Extract Frontend
  include_role:
    name: common
    tasks_from: download

- name: Clenup fold html ile
  ansible.builtin.file:
    path: /home/roboshop/catalogue
    state: absent

- name: Copy app content
  ansible.builtin.copy:
    src: /tmp/catalogue-main/
    dest: /home/roboshop/catalogue/
    remote_src: yes
  become_user: roboshop

- name: Install NodeJS Dependencies based on package.json
  community.general.npm:
    path: /home/roboshop/catalogue
  become_user: roboshop

- name: Copy SystemD File
  ansible.builtin.template:
    src: systemd.service
    dest: /etc/systemd/system/catalogue.service