- name: Configure YUM repos.
  ansible.builtin.shell: curl -fsSL https://rpm.nodesource.com/setup_lts.x | bash -

- name: Install NodeJS
  ansible.builtin.yum:
    name:
      - nodejs
      - gcc-c++
    state: installed