- name: Download and extract {{COMPONENT}}
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/{{COMPONENT}}/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: Start catalogue Service
  ansible.builtin.systemd:
    name: catalogue
    state: restarted
    enabled: yes
    daemon_reload: yes